// <auto-generated />
using HandsonTable_project_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandsonTable_project_WebAPI.Migrations
{
    [DbContext(typeof(HandsonTableDbContext))]
    [Migration("20220508173629_migration02")]
    partial class migration02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HandsonTable_project_WebAPI.Models.HandsontableDataModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<double>("capacity1")
                        .HasColumnType("float");

                    b.Property<double>("capacity2")
                        .HasColumnType("float");

                    b.Property<double>("capacity3")
                        .HasColumnType("float");

                    b.Property<double>("capacity4")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<double>("skill1")
                        .HasColumnType("float");

                    b.Property<double>("skill2")
                        .HasColumnType("float");

                    b.Property<double>("skill3")
                        .HasColumnType("float");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HandsontableDataModels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "A"
                        },
                        new
                        {
                            id = 2,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "B"
                        },
                        new
                        {
                            id = 3,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "C"
                        },
                        new
                        {
                            id = 4,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "D"
                        },
                        new
                        {
                            id = 5,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "E"
                        },
                        new
                        {
                            id = 6,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "F"
                        },
                        new
                        {
                            id = 7,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "G"
                        },
                        new
                        {
                            id = 8,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "H"
                        },
                        new
                        {
                            id = 9,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "I"
                        },
                        new
                        {
                            id = 10,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "J"
                        },
                        new
                        {
                            id = 11,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "k"
                        },
                        new
                        {
                            id = 12,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "L"
                        },
                        new
                        {
                            id = 13,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "M"
                        },
                        new
                        {
                            id = 14,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "N"
                        },
                        new
                        {
                            id = 15,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "O"
                        },
                        new
                        {
                            id = 16,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "P"
                        },
                        new
                        {
                            id = 17,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "Q"
                        },
                        new
                        {
                            id = 18,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "R"
                        },
                        new
                        {
                            id = 19,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "S"
                        },
                        new
                        {
                            id = 20,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "T"
                        },
                        new
                        {
                            id = 21,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "AA"
                        },
                        new
                        {
                            id = 22,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "BA"
                        },
                        new
                        {
                            id = 23,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "CA"
                        },
                        new
                        {
                            id = 24,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "DA"
                        },
                        new
                        {
                            id = 25,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "EA"
                        },
                        new
                        {
                            id = 26,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "FA"
                        },
                        new
                        {
                            id = 27,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "GA"
                        },
                        new
                        {
                            id = 28,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "HA"
                        },
                        new
                        {
                            id = 29,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "IA"
                        },
                        new
                        {
                            id = 30,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "JA"
                        },
                        new
                        {
                            id = 31,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "kA"
                        },
                        new
                        {
                            id = 32,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "LA"
                        },
                        new
                        {
                            id = 33,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "MA"
                        },
                        new
                        {
                            id = 34,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "NA"
                        },
                        new
                        {
                            id = 35,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "OA"
                        },
                        new
                        {
                            id = 36,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "PA"
                        },
                        new
                        {
                            id = 37,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "QA"
                        },
                        new
                        {
                            id = 38,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "RA"
                        },
                        new
                        {
                            id = 39,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "SA"
                        },
                        new
                        {
                            id = 40,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "TA"
                        },
                        new
                        {
                            id = 41,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "AB"
                        },
                        new
                        {
                            id = 42,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "BB"
                        },
                        new
                        {
                            id = 43,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "CB"
                        },
                        new
                        {
                            id = 44,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "DB"
                        },
                        new
                        {
                            id = 45,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "EB"
                        },
                        new
                        {
                            id = 46,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "FB"
                        },
                        new
                        {
                            id = 47,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "GB"
                        },
                        new
                        {
                            id = 48,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "HB"
                        },
                        new
                        {
                            id = 49,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "IB"
                        },
                        new
                        {
                            id = 50,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "JB"
                        },
                        new
                        {
                            id = 51,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "kB"
                        },
                        new
                        {
                            id = 52,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "LB"
                        },
                        new
                        {
                            id = 53,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "MB"
                        },
                        new
                        {
                            id = 54,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "NB"
                        },
                        new
                        {
                            id = 55,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "OB"
                        },
                        new
                        {
                            id = 56,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "PB"
                        },
                        new
                        {
                            id = 57,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "QB"
                        },
                        new
                        {
                            id = 58,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "RB"
                        },
                        new
                        {
                            id = 59,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "SB"
                        },
                        new
                        {
                            id = 60,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "TB"
                        },
                        new
                        {
                            id = 61,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "AAB"
                        },
                        new
                        {
                            id = 62,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "BAB"
                        },
                        new
                        {
                            id = 63,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "CAB"
                        },
                        new
                        {
                            id = 64,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "DAB"
                        },
                        new
                        {
                            id = 65,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "EAB"
                        },
                        new
                        {
                            id = 66,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "FAB"
                        },
                        new
                        {
                            id = 67,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "GAB"
                        },
                        new
                        {
                            id = 68,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "HAB"
                        },
                        new
                        {
                            id = 69,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "IAB"
                        },
                        new
                        {
                            id = 70,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "JAB"
                        },
                        new
                        {
                            id = 71,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "kAB"
                        },
                        new
                        {
                            id = 72,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "LAB"
                        },
                        new
                        {
                            id = 73,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "MAB"
                        },
                        new
                        {
                            id = 74,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "NAB"
                        },
                        new
                        {
                            id = 75,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "OAB"
                        },
                        new
                        {
                            id = 76,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "PAB"
                        },
                        new
                        {
                            id = 77,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "QAB"
                        },
                        new
                        {
                            id = 78,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "RAB"
                        },
                        new
                        {
                            id = 79,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "SAB"
                        },
                        new
                        {
                            id = 80,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "TAB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
