// <auto-generated />
using HandsonTable_project_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandsonTable_project_WebAPI.Migrations
{
    [DbContext(typeof(HandsonTableDbContext))]
    partial class HandsonTableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HandsonTable_project_WebAPI.Models.HandsontableDataModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<double>("capacity1")
                        .HasColumnType("float");

                    b.Property<double>("capacity2")
                        .HasColumnType("float");

                    b.Property<double>("capacity3")
                        .HasColumnType("float");

                    b.Property<double>("capacity4")
                        .HasColumnType("float");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<double>("skill1")
                        .HasColumnType("float");

                    b.Property<double>("skill2")
                        .HasColumnType("float");

                    b.Property<double>("skill3")
                        .HasColumnType("float");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HandsontableDataModels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "A"
                        },
                        new
                        {
                            id = 2,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "B"
                        },
                        new
                        {
                            id = 3,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "C"
                        },
                        new
                        {
                            id = 4,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "D"
                        },
                        new
                        {
                            id = 5,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.40000000000000002,
                            skill3 = 0.29999999999999999,
                            unit = "E"
                        },
                        new
                        {
                            id = 6,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "F"
                        },
                        new
                        {
                            id = 7,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "G"
                        },
                        new
                        {
                            id = 8,
                            capacity1 = 0.29999999999999999,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "H"
                        },
                        new
                        {
                            id = 9,
                            capacity1 = 0.40000000000000002,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.40000000000000002,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.40000000000000002,
                            unit = "I"
                        },
                        new
                        {
                            id = 10,
                            capacity1 = 0.20000000000000001,
                            capacity2 = 0.20000000000000001,
                            capacity3 = 0.20000000000000001,
                            capacity4 = 0.20000000000000001,
                            rate = 0.5,
                            skill1 = 0.5,
                            skill2 = 0.20000000000000001,
                            skill3 = 0.29999999999999999,
                            unit = "J"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
